### ISSUE TITLE
Better reading(s) for tidy-eval?

### ISSUE THREAD

**Issue by behrman** [dcl-2019-01/curriculum#18]
Are any of the [readings in the new Advanced R book](https://adv-r.hadley.nz/quasiquotation.html) useful for tidy-eval?

**Comment by behrman** [comment]
Is [Programming with dplyr](https://dplyr.tidyverse.org/articles/programming.html) a better reading?

**Comment by behrman** [comment]
Another possible reading:

* [TIdy evaluation](https://tidyeval.tidyverse.org)

A possible supplemental reading:

* [Tidyeval](https://ijlyttle.shinyapps.io/tidyeval/)

**Comment by skaltman** [comment]
there's also a [cheat sheet](https://github.com/rstudio/cheatsheets/blob/master/tidyeval.pdf) which looks like it could be useful.
