### ISSUE TITLE
build not properly creating links

### ISSUE THREAD

**Issue by behrman** [dcl-2019-01/curriculum#23]
@hadley The build of [separate-unite.yml](https://github.com/dcl-2019-01/curriculum/blob/master/units/separate-unite.yml) didn't work. The last reading didn't convert into a link: [built page](https://dcl-2019-01.github.io/curriculum/separate-unite.html). Is there something we're doing wrong?

**Comment by hadley** [comment]
Shouldn't it be `href`, not `html`?

**Comment by behrman** [comment]
That was it. Thanks!
