### ISSUE TITLE
unable to remove discontinued units

### ISSUE THREAD

**Issue by behrman** [dcl-2019-01/curriculum#24]
@hadley The build system has worked very well. We've added a number of new units. However, we've encountered problems trying to remove, discontinued units. When we try removing units, the build breaks.

**Comment by hadley** [comment]
Do you have an example? You should be able to delete the file and delete the record from `syllabus.yml`

**Comment by behrman** [comment]
Good. For the curriculum repo for next quarter, we'll try deleting files that are no longer needed and no longer in `syllabus.yml`. This will either work, or we'll have an example.

Thanks!

**Comment by behrman** [comment]
I was able to separate the unused units (which were showing up on the dependency plot). I think the problem we had in the past was due to not deleting dependency links. Thanks.
